### ISSUE TITLE
Setting resources.disk doesn't seem to work

### ISSUE THREAD

**Issue by samos123** [substratusai/substratus#247]
```
apiVersion: substratus.ai/v1
kind: Notebook
metadata:
  name: k8s-instruct-dataset
spec:
  suspend: true
  build:
    git:
      url: https://github.com/substratusai/images
      path: base
  resources:
    disk: 300
```

I was expecting a 300GB ephemeral disk request but doesn't seem like that happened
