### ISSUE TITLE
Store models outside of containers

### ISSUE THREAD

**Issue by nstogner** [substratusai/substratus#68]
Storing models outside of containers could help with:

1. Loading models into different environments. (A notebook/dev environment could be separate from a production serving environment).
2. Allowing for users to iterate on the same models with different libraries (see #67).

A Model object in this case would operate closer to a Dataset (where an importer is defined that will load in a model to be saved).

Underlying storage would likely be a FUSE-mounted bucket.

**Comment by samos123** [comment]
I'm imagining a container images that has a train.ipynb and inference that works with majority of HF models out of the box and then all it needs is to have a specific model loaded at runtime at /model/saved?

How do you see the CRDs evolving?


Draft, this is how I'm imaging it possibly working once we separate the model
```
kind: Model
name: falcon-7b
spec:
  source: hf://falcon-7b
status: gs://model/falcon-7b/
```

Fine tuned model would be created 
```
kind: FinetuningJob
spec:
  image: substratusai/hf-finetuner
  model: falcon-7b
  dataset: k8s-instructions
  outputModelName: falcon-7b-finetuned
  gpu_type: a100_80b
  gpu_count: 8
```

Serving:
```
kind: ModelServer
spec:
  image: substratusai/hf-modelserver
  model: falcon-7b-finetuned
  gpu_count: 1
  gpu_type: L4
```
